# Generated by Django 4.2.7 on 2024-02-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAF', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='level',
        ),
    ]
