# Generated by Django 4.2.7 on 2024-02-21 08:16

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAF', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name=django.contrib.auth.models.User),
        ),
    ]
