# Generated by Django 4.2.7 on 2024-03-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAF', '0008_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, default='book.jpg', upload_to='media')),
                ('body', models.TextField()),
            ],
        ),
    ]
