# Generated by Django 4.2.7 on 2024-03-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAF', '0009_maincourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
