# Generated by Django 4.2.7 on 2024-03-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAF', '0010_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Join',
        ),
    ]
